# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientConsult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('msg', models.TextField()),
                ('from_client', models.BooleanField()),
                ('source', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientFollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField()),
                ('result', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.PositiveIntegerField(null=True)),
                ('qq', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('volume', models.PositiveIntegerField()),
                ('start_time', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Area')),
            ],
        ),
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysname', models.CharField(max_length=30, unique=True)),
                ('cname', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('女', '女'), ('男', '男')], max_length=3)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=64)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('area', models.ManyToManyField(to='webapp.Area')),
            ],
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('gender', models.BooleanField()),
                ('phone', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ClientInfo')),
                ('courses', models.ManyToManyField(to='webapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('test_at', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Course')),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.StudentStatus'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.StaffInfo'),
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='roles',
            field=models.ManyToManyField(to='webapp.StaffRole'),
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.StaffStatus'),
        ),
        migrations.AddField(
            model_name='course',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.StudentInfo'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(to='webapp.StaffInfo'),
        ),
        migrations.AddField(
            model_name='clientfollowup',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ClientInfo'),
        ),
        migrations.AddField(
            model_name='clientfollowup',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.StaffInfo'),
        ),
        migrations.AddField(
            model_name='clientconsult',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ClientInfo'),
        ),
        migrations.AddField(
            model_name='clientconsult',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.StaffInfo'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.StudentInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='studentinfo',
            unique_together=set([('name', 'gender', 'phone')]),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('name', 'volume', 'area')]),
        ),
    ]
