# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20170119_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='updated_by',
        ),
    ]
