# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_studentinfo_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.ClientInfo'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='webapp.Course'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
