# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20170119_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Area'),
            preserve_default=False,
        ),
    ]
