# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20170122_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursescore',
            name='test_at',
        ),
    ]
