# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20170123_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('client_ip', models.GenericIPAddressField()),
                ('source', models.CharField(default='web', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.ClientInfo')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.StaffInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='clientconsult',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientconsult',
            name='source',
        ),
        migrations.RemoveField(
            model_name='clientconsult',
            name='staff',
        ),
        migrations.AlterField(
            model_name='clientconsult',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.SessionTokens'),
        ),
    ]
