# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20170128_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontokens',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
