# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_sessiontokens_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.SessionTokens'),
        ),
    ]
