# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_clientinfo_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='webapp.ClientInfo'),
        ),
    ]
