# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20170131_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='source',
            field=models.CharField(choices=[('consult', '客户咨询'), ('manual', '手工添加')], default='consult', max_length=20),
        ),
    ]
