# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_clientinfo_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='dont_follow',
            field=models.BooleanField(default=False),
        ),
    ]
