# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_auto_20170201_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='from_staff',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='webapp.StaffInfo'),
            preserve_default=False,
        ),
    ]
