# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_auto_20170201_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='qq',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
