# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_auto_20170201_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='qq',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=3, null=True),
        ),
    ]
