# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20170215_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
