# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20170213_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(error_messages={'unique': '昵称已被占用'}, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '邮箱已被注册'}, max_length=254, unique=True),
        ),
    ]
