# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20170213_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='post',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='img_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
