# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170117_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffinfo',
            name='area',
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Area'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='staffinfo',
            name='roles',
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='roles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.StaffRole'),
            preserve_default=False,
        ),
    ]
