# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170117_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=64, verbose_name='课程名称'),
        ),
    ]
