# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170117_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinfo',
            name='password',
            field=models.CharField(max_length=64, verbose_name='password'),
        ),
    ]
