# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20170118_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinfo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Area', verbose_name='属区'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='cname',
            field=models.CharField(max_length=30, verbose_name='中文名'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=3, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.StaffRole', verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.StaffStatus', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='staffinfo',
            name='sysname',
            field=models.CharField(max_length=30, unique=True, verbose_name='登录名'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=3),
        ),
    ]
