# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_studentinfo_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='courses',
            field=models.ManyToManyField(to='webapp.Course'),
        ),
    ]
