# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20170122_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescore',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.StudentInfo'),
            preserve_default=False,
        ),
    ]
