# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20170126_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientconsult',
            old_name='session_id',
            new_name='session',
        ),
    ]
