# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_clientinfo_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='source',
            field=models.CharField(choices=[('consult', 'consult'), ('manual', 'manual')], default='consult', max_length=20),
        ),
    ]
