# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_auto_20170131_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
