# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_clientinfo_dont_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfollowup',
            name='follow_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
