# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_clientinfo_from_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='from_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.StaffInfo'),
        ),
    ]
