# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_auto_20170201_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
