# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-12 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_course_avg_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='avg_score',
        ),
    ]
